pipeline{
    agent any 
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage("sonar-scan"){
            steps{
                withSonarQubeEnv('sonarQube'){
sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Hero2013_geo-app1'
                }
            
            }
        }
        stage("maven"){
            steps{
            sh 'mvn clean'
            sh 'mvn validate'
            sh 'mvn compile'
            sh 'mvn install'
            sh 'mvn test' 
            sh 'mvn package'
        }
    }
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP5hovDc2p15yy6qPUt69bTZWL3 -T \
    target/bio*.jar \
    "http://54.90.31.101:8081/artifactory/geosolution/file1/bio-${BUILD_ID}.jar"'
        }
    }
}
}